simulator:
  pools:
    usdc_dai_100: [1.0, 1.0]

  model:
    steps: 500
    random_seed: 1234

  agents:
    minnow:
      num: 100
      fund:
        usdc: 10_000
        dai: 10_000
      diff_factor: 0.01
      swap_amount: 100
      hodl_swap_probability: 0.5

    whale:
      num: 3
      fund:
        usdc: 1_000_000
        dai: 1_000_000
      dump: 5_000

    lp:
      num: 10
      fund:
        dai: 10_000
        usdc: 10_000
      initial_position:
        dai: 1000
        usdc: 1000
        range: [
          [0.97, 1.05],
          [0.98, 1.0],
          [0.985, 1.01],
          [0.99, 1.03],
          [0.997, 1.01],
        ]
