simulator:
  random_seed: 1234

  # Do not change. Only valid Uniswap v3 fee range
  fees:
    - 0.01
    - 0.05
    - 0.30
    - 1.0

  pools:
    dia_usdc:
      tokens:
        0: "dai"
        1: "usdc"
      fee: ${simulator.fees[1]} # 0.05 fee
      price: 1.0

  model:
    steps: 500
    output:
      save: false
      trading: "./data/trading.parquet"
      liquidity: "./data/liquidity.parquet"

  agents:
    minnow:
      num: 100
      fund:
        dia: 10_000
        usdc: 10_000
      diff_factor: 0.01
      swap_amount: 100
      hodl_swap_probability: 0.5

    whale:
      num: 3
      fund:
        dia: 1_000_000
        usdc: 1_000_000
      dump: 15_000

    lp:
      num: 10
      fund:
        dia: 10_000
        usdc: 10_000
      initial_position:
        dia: 1000
        usdc: 1000
        range: [
          [0.97, 1.05],
          [0.98, 1.0],
          [0.985, 1.01],
          [0.99, 1.03],
          [0.997, 1.01],
        ]
      # randomly selected token value to increase liquidity
      increase_range: [500, 1000]
      # randomly selected percentage ranges to decrease liquidity
      decrease_range: [5, 20]
