simulator:
  pools:
    dia_usdc:
      tokens:
        0: "dai"
        1: "usdc"
      fee: 0.01
      price: 1.0

  model:
    steps: 100
    output:
      save: false
      trading: "./basictrading.parquet"
      liquidity: "./basicliquidity.parquet"

  agents:
    zi:
      num: 100
      fund:
        dia: 10_000
        usdc: 10_000
      swap_amount: 100
      swap_probability: 0.5

    lp:
      num: 1
      fund:
        dia: 50_000
        usdc: 50_000
      positions:
        amounts: 20_000
        ranges: [[0.97, 1.02], [0.99, 1.01]]
